server:
  port: 8080
message:
  entity-not-found: Entity not found.
  internal-server-error: Internal server error. Please, contact system administrator.
  template:
    validation-error: Field %s %s
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: a5b8a3602b17e8ac94bb
            client-secret: fd21fa52d5e0d6e3461bfeaa6a8f12df3e8934c0
            client-name: USER
            provider: github
            scope: no-scope
            redirect-uri-template: http://localhost:8080/login/oauth2/code/github